version: 0.2
phases:
 install:
  runtime-versions:
   python: 3.12
  commands:
   - pip install --upgrade pip
   # Install dependencies needed for running the static analysis
   - pip install -r requirements.txt pylint
   
 pre_build:
  commands:
   - python --version
   - pylint $CODEBUILD_SRC_DIR/*.py
   - pylint --disable=E1101,R1705,W0718,C0116,C0325,W0612,C0103,C0115 $CODEBUILD_SRC_DIR/scmapp/*.py
   - pylint --disable=C0301,C0103 $CODEBUILD_SRC_DIR/SCM/*.py
   


   
artifacts:
 files:
  - '**/*'
